config/routes.rb
Rails.application.routes.draw do
  resources :annotations
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "annotations#index"
  get '/search', to: 'annotations#search'
end

app/models/annotation.rb
class Annotation < ApplicationRecord
  scope :search_title_or_annotation, -> (title) { where("unaccent(title)  ILIKE unaccent(?) OR unaccent(annotation) ILIKE unaccent(?)", "%#{title}%", "%#{title}")}

  belongs_to :user
  enum priority:  [:baixa, :media, :alta]
  validates :title, :annotation, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :annotations
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: %i[ show edit update destroy ]

  # GET /annotations or /annotations.json
  def index
    @annotation = Annotation.new
    if params[:q]
      @annotations = Annotation.where(user_id: current_user.id).page(params[:page]).per(3).search_title_or_annotation(params[:q]).order(priority: "desc")
    else
      @annotations = Annotation.where(user_id: current_user.id).page(params[:page]).per(3).order(priority: "desc")
    end
  end

  def search
    @annotations = Annotation.where(user_id: current_user.id).search_title_or_annotation(params[:q])
  end

  # GET /annotations/1 or /annotations/1.json
  def show
    unless @annotation[:user_id] == current_user.id
      redirect_to root_path , alert: "Só pode acessar suas anotaçoes"
    end
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
    unless @annotation[:user_id] == current_user.id
      redirect_to root_path , alert: "Só pode Editar suas anotaçoes"
    end
  end

  # POST /annotations or /annotations.json
  def create
    @annotation = Annotation.new(annotation_params) 
    @annotation.user_id = current_user.id

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to root_path, notice: "Anotação criada com sucesso." }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1 or /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to @annotation, notice: "Anotação atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1 or /annotations/1.json
  def destroy
    @annotation.destroy
    respond_to do |format|
      format.html { redirect_to annotations_url, notice: "Anotação foi deletada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def annotation_params
      params.require(:annotation).permit(:title, :annotation, :date, :priority)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annotations/_form.html.erb
<%= form_with(model: annotation, local: true ) do |form| %>
  <% if annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(annotation.errors.count, "error") %> impediu que anotação fosse salva:</h2>

      <ul>
        <% annotation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class:"form-control", placeholder:"Título", required: true, errors: "Título não pode ser vazio" %>
  </div>

  <div class="form-group">
    <%= form.text_area :annotation, class:"form-control", placeholder:"Anotação", required: true %>
  </div>

  <div class="form-group">
    <%= form.label "#{t 'annotation.date'}" %>
    <%= form.date_select :date, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "#{t 'annotation.priority'}" %>
    <%= form.select(:priority, Annotation.priorities.keys, {}) %>
  </div>

  <div class="actions">
    <%= link_to "#{t('actions.back')}", root_path, class:"btn btn-secondary" %>
    <%= submit_tag("Salvar Anotação", :class=>"btn btn-primary", :name=>"submit") %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
 <div class="row justify-content-center">
  <div class="col-xl-6 col-lg-12 col-md-9">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Editar Anotação</h1>
              </div>
                <%= render 'form', annotation: @annotation %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/annotations/index.html.erb
 <div class="row justify-content-center">
  <div class="col-xl-12 col-lg-12 col-md-12">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Anotações</h1>
              </div>
                <%= form_tag("/annotations", method: "get", class:"form-inline my-2 my-lg-0") do %>
                <%= label_tag(:q, "buscar anotações:") %>
                <%= text_field_tag(:q) %>
                <%= submit_tag("#{t('actions.search')}", class:"btn btn-outline-success my-2 my-sm-0") %>
              <% end %>

              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col"><%= t 'annotation.title' %></th>
                    <th scope="col"><%= t 'annotation.annotation' %></th>
                    <th scope="col"><%= t 'annotation.date' %></th>
                    <th scope="col"><%= t 'annotation.priority' %></th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                

                <tbody>
                  <% @annotations.each do |annotation| %>
                    <tr>
                      <td><%= annotation.title %></td>
                      <td><%= annotation.annotation %></td>
                      <td><%= annotation.date %></td>
                      <td><%= annotation.priority %></td>
                      <td><%= link_to "#{t('actions.show')}" , annotation, class:"btn btn-primary" %></td>
                      <td><%= link_to "#{t('actions.edit')}", edit_annotation_path(annotation), class:"btn btn-info" %></td>
                      <td><%= link_to "#{t('actions.destroy')}", annotation_path(annotation), class:"btn btn-danger", :method => :delete, data: { confirm: 'Tem certeza que deseja deletar?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

                <hr>
                <%= paginate @annotations, left: 1, right: 3 %>
                <hr>

              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                <%= "#{t('helpers.submit.create', model: "Anotação" )}" %>
              </button>
              <%= link_to "Sair", destroy_user_session_path, :method => :delete, class:"btn btn-primary", data: { confirm: 'Tem certeza que quer sair?' } %>

              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Nova Anotação</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= render 'form', annotation: @annotation %>
                    </div>
                  </div>
                </div>
              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/annotations/new.html.erb
 <div class="row justify-content-center">
  <div class="col-xl-6 col-lg-12 col-md-9">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Nova Anotação</h1>
              </div>
                <%= render 'form', annotation: @annotation %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/annotations/show.html.erb
 <div class="row justify-content-center">
  <div class="col-xl-10 col-lg-12 col-md-10">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Exibir Anotação</h1>
              </div>
                <p>
                <strong><%= t 'annotation.title' %>:</strong>
                <%= @annotation.title %>
              </p>

              <p>
                <strong><%= t 'annotation.annotation' %>:</strong>
                <%= @annotation.annotation %>
              </p>

              <p>
                <strong><%= t 'annotation.date' %>:</strong>
                <%= @annotation.date %>
              </p>

              <p>
                <strong><%= t 'annotation.priority' %>:</strong>
                <%= @annotation.priority %>
              </p>

              <%= link_to "#{t('actions.edit')}", edit_annotation_path(@annotation), class:"btn btn-primary" %> 
              <%= link_to "#{t('actions.back')}", annotations_path,  class:"btn btn-secondary" %>
            </div
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Talentbrand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-dark">
    <div class="container">
      <%= yield %>
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show float-right" role="alert">
          <p class="text-justify"><%= notice %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        <% end %>
        <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show float-right"  role="alert">
          <p class="text-justify"><%= alert %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
    <% end %>
    </div>
  </body>
</html>